#!/usr/bin/env python3
"""
render_report.py - Stage 2 of the data pipeline.

Reads stats.json and renders a formatted report.
Supports markdown (default) and HTML output.

Usage:
    python3 render_report.py <stats.json> [--output <report.md>] [--format md|html]
    python3 render_report.py workspace/stats.json
    python3 render_report.py workspace/stats.json --output workspace/report.md
    python3 render_report.py workspace/stats.json --format html --output workspace/report.html
"""

import argparse
import json
import sys
import os
from datetime import datetime


def parse_args():
    parser = argparse.ArgumentParser(
        description="Render a claims report from stats.json"
    )
    parser.add_argument("stats_json", help="Path to stats.json produced by analyze.py")
    parser.add_argument(
        "--output",
        default="workspace/report.md",
        help="Output file path (default: workspace/report.md)",
    )
    parser.add_argument(
        "--format",
        choices=["md", "html"],
        default="md",
        help="Output format: md or html (default: md)",
    )
    return parser.parse_args()


def load_stats(filepath):
    """Load and validate stats.json."""
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    required_keys = {"total_records", "total_amount", "by_category", "by_status"}
    missing = required_keys - set(data.keys())
    if missing:
        print(f"Error: stats.json missing keys: {', '.join(missing)}", file=sys.stderr)
        sys.exit(1)

    return data


def render_markdown(stats):
    """Render a markdown report from stats."""
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = []

    lines.append("# Claims Analysis Report")
    lines.append("")
    lines.append(f"*Generated: {generated_at}*")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Executive summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total Claims | {stats['total_records']:,} |")
    lines.append(f"| Total Billed | ${stats['total_amount']:,.2f} |")
    avg = stats.get("overall_average", 0)
    lines.append(f"| Average per Claim | ${avg:,.2f} |")
    lines.append(f"| Categories | {len(stats['by_category'])} |")
    lines.append("")

    # Claims by category
    lines.append("## Claims by Category")
    lines.append("")
    lines.append("| Category | Count | Total Billed | Avg per Claim | Min | Max |")
    lines.append("|----------|-------|-------------|---------------|-----|-----|")

    for category, data in sorted(
        stats["by_category"].items(), key=lambda x: x[1]["total"], reverse=True
    ):
        count = data["count"]
        total = data["total"]
        avg = data["average"]
        min_val = data["min"]
        max_val = data["max"]

        # Calculate percentage of total
        pct = (total / stats["total_amount"] * 100) if stats["total_amount"] > 0 else 0

        lines.append(
            f"| {category.replace('_', ' ').title()} | {count:,} | ${total:,.2f} ({pct:.1f}%) | ${avg:,.2f} | ${min_val:,.2f} | ${max_val:,.2f} |"
        )

    lines.append("")

    # Claims by status
    lines.append("## Claims by Status")
    lines.append("")
    lines.append("| Status | Count | Total |")
    lines.append("|--------|-------|-------|")

    for status, data in sorted(stats["by_status"].items()):
        lines.append(
            f"| {status.title()} | {data['count']:,} | ${data['total']:,.2f} |"
        )

    lines.append("")

    # Key highlights
    lines.append("## Key Highlights")
    lines.append("")

    if stats["by_category"]:
        top_cat = max(stats["by_category"].items(), key=lambda x: x[1]["total"])
        lines.append(
            f"- **Highest spend category:** {top_cat[0].replace('_', ' ').title()} "
            f"(${top_cat[1]['total']:,.2f})"
        )

        top_count = max(stats["by_category"].items(), key=lambda x: x[1]["count"])
        lines.append(
            f"- **Most frequent category:** {top_count[0].replace('_', ' ').title()} "
            f"({top_count[1]['count']} claims)"
        )

    if "approved" in stats["by_status"]:
        approved = stats["by_status"]["approved"]
        approval_pct = (
            approved["count"] / stats["total_records"] * 100
        ) if stats["total_records"] > 0 else 0
        lines.append(f"- **Approval rate:** {approval_pct:.1f}%")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by Data Pipeline Agent*")

    return "\n".join(lines)


def render_html(stats):
    """Render an HTML report from stats."""
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Build category rows
    category_rows = []
    for category, data in sorted(
        stats["by_category"].items(), key=lambda x: x[1]["total"], reverse=True
    ):
        pct = (data["total"] / stats["total_amount"] * 100) if stats["total_amount"] > 0 else 0
        category_rows.append(
            f"<tr>"
            f"<td>{category.replace('_', ' ').title()}</td>"
            f"<td>{data['count']:,}</td>"
            f"<td>${data['total']:,.2f} ({pct:.1f}%)</td>"
            f"<td>${data['average']:,.2f}</td>"
            f"<td>${data['min']:,.2f}</td>"
            f"<td>${data['max']:,.2f}</td>"
            f"</tr>"
        )

    status_rows = []
    for status, data in sorted(stats["by_status"].items()):
        status_rows.append(
            f"<tr><td>{status.title()}</td><td>{data['count']:,}</td>"
            f"<td>${data['total']:,.2f}</td></tr>"
        )

    avg = stats.get("overall_average", 0)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Claims Analysis Report</title>
  <style>
    body {{ font-family: Arial, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #333; }}
    h1 {{ color: #1a237e; border-bottom: 2px solid #1a237e; padding-bottom: 8px; }}
    h2 {{ color: #283593; margin-top: 30px; }}
    .subtitle {{ color: #666; font-style: italic; margin-bottom: 20px; }}
    .summary-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 20px 0; }}
    .stat-card {{ background: #e8eaf6; border-radius: 8px; padding: 16px; text-align: center; }}
    .stat-card .value {{ font-size: 24px; font-weight: bold; color: #1a237e; }}
    .stat-card .label {{ font-size: 12px; color: #555; margin-top: 4px; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
    th {{ background: #1a237e; color: white; padding: 10px 12px; text-align: left; }}
    td {{ padding: 9px 12px; border-bottom: 1px solid #e0e0e0; }}
    tr:hover {{ background: #f5f5f5; }}
    .footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid #e0e0e0; color: #888; font-size: 12px; }}
  </style>
</head>
<body>
  <h1>Claims Analysis Report</h1>
  <p class="subtitle">Generated: {generated_at}</p>

  <h2>Executive Summary</h2>
  <div class="summary-grid">
    <div class="stat-card">
      <div class="value">{stats['total_records']:,}</div>
      <div class="label">Total Claims</div>
    </div>
    <div class="stat-card">
      <div class="value">${stats['total_amount']:,.2f}</div>
      <div class="label">Total Billed</div>
    </div>
    <div class="stat-card">
      <div class="value">${avg:,.2f}</div>
      <div class="label">Average per Claim</div>
    </div>
    <div class="stat-card">
      <div class="value">{len(stats['by_category'])}</div>
      <div class="label">Categories</div>
    </div>
  </div>

  <h2>Claims by Category</h2>
  <table>
    <thead>
      <tr>
        <th>Category</th><th>Count</th><th>Total Billed</th>
        <th>Avg per Claim</th><th>Min</th><th>Max</th>
      </tr>
    </thead>
    <tbody>
      {''.join(category_rows)}
    </tbody>
  </table>

  <h2>Claims by Status</h2>
  <table>
    <thead>
      <tr><th>Status</th><th>Count</th><th>Total</th></tr>
    </thead>
    <tbody>
      {''.join(status_rows)}
    </tbody>
  </table>

  <div class="footer">Report generated by Data Pipeline Agent</div>
</body>
</html>"""

    return html


def main():
    args = parse_args()

    if not os.path.isfile(args.stats_json):
        print(f"Error: Stats file not found: {args.stats_json}", file=sys.stderr)
        sys.exit(1)

    print(f"  Loading: {args.stats_json}", file=sys.stderr)
    stats = load_stats(args.stats_json)

    if args.format == "md":
        content = render_markdown(stats)
    else:
        content = render_html(stats)

    # Ensure output directory exists
    output_dir = os.path.dirname(args.output)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"  Written: {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
